package ru.iprustam.trainee.simbirchat.util.role;

public enum ChatAuthorities {
    USER_BLOCKING, USER_UNBLOCKING, MODERATOR_SET, MODERATOR_DELETE,
    MESSAGE_SEND, MESSAGE_RECEIVE, MESSAGE_DELETE, PUBLIC_ROOM_CREATE,
    PRIVATE_ROOM_CREATE, USER_ADD, USER_DELETE, ROOM_RENAME
}
