package ru.iprustam.trainee.simbirchat.util.role;

public enum ChatAuthority {
    USER_BAN, USER_UNBAN, MODERATOR_SET, MODERATOR_DELETE,
    MESSAGE_SEND, MESSAGE_RECEIVE, MESSAGE_DELETE, PUBLIC_ROOM_CREATE,
    PRIVATE_ROOM_CREATE, ROOM_CONNECT, USER_DELETE, ROOM_RENAME,
    ROOM_REMOVE, USER_RENAME
}
