DROP TABLE if exists role CASCADE;
DROP TABLE if exists room CASCADE;
DROP TABLE if exists usr CASCADE;
DROP TABLE if exists message CASCADE;
DROP TABLE if exists room_user CASCADE;

create table role (role_id int2 generated by default as identity, role_name varchar(255), primary key (role_id));

create table message (message_id int8 generated by default as identity, message varchar(255), message_time timestamp, room_id int8 not null, user_id int8 not null, primary key (message_id));

create table room (room_id int8 generated by default as identity, room_type int4, primary key (room_id));

create table room_user (room_id int8 not null, user_id int8 not null, primary key (room_id, user_id));

create table usr (user_id int8 generated by default as identity, password varchar(255), username varchar(255), role_id int2 not null, primary key (user_id));

alter table if exists message add constraint room_id_fkey foreign key (room_id) references room ON DELETE CASCADE;
alter table if exists message add constraint user_id_fkey foreign key (user_id) references usr ON DELETE CASCADE;
alter table if exists room_user add constraint user_id_fkey foreign key (user_id) references usr ON DELETE CASCADE;
alter table if exists room_user add constraint room_id_fkey foreign key (room_id) references room ON DELETE CASCADE;
alter table if exists usr add constraint role_id_fkey foreign key (role_id) references role ;

INSERT INTO role (role_name) VALUES
  ('ADMIN'), 
  ('MODERATOR'), 
  ('USER'),
  ('BOT');